### ISSUE TITLE
Does server need to be restarted any time you post a new face?

### ISSUE THREAD

**Issue by Trisystema** [Zulkarnine1/Face-Recognition-Nodejs-MongoDB#1]
Not an issue per se, but reading your code I'd say one would need to restart the server whenever there's a new face posted?

**Comment by Zulkarnine1** [comment]
@Trisystema I don't think so. That shouldn't be the case as essentially we would be storing all the face descriptors in the database whenever a face is posted, and when a face is to be checked if it's for the valid user, we would use the `getDescriptorsFromDB` function to get all the face data from the database and cross-check if the user matches or no. This project wasn't done to scale, I think different approaches can be taken to scale it for large amount of users, I tried to keep it simple so that the blog is easier to understand.

**Comment by Trisystema** [comment]
> @Trisystema I don't think so. That shouldn't be the case as essentially we would be storing all the face descriptors in the database whenever a face is posted, and when a face is to be checked if it's for the valid user, we would use the `getDescriptorsFromDB` function to get all the face data from the database and cross-check if the user matches or no. This project wasn't done to scale, I think different approaches can be taken to scale it for large amount of users, I tried to keep it simple so that the blog is easier to understand.

Ah sorry I've misunderstood, now I see that you pull all database entries when a client load. Thanks!
